name: idrenew_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Machine Learning
  tflite_flutter: ^0.10.4  # Runs TensorFlow Lite models
  image: ^4.0.17           # Image processing (resize, format conversion)


  # Camera
  camera: ^0.10.5+5

  # Camera & Image Selection
  image_picker: ^1.0.4     # Take photos or pick from gallery
  flutter_svg: ^2.0.10+1

  # Firebase (for Step 5)
  firebase_core: ^2.24.2   # Firebase initialization
  cloud_firestore: ^4.13.6 # Database to store scan history

  # UI Helpers
  intl: ^0.18.1            # Date formatting

  # ðŸ’¾ Storage & Preferences
  shared_preferences: ^2.2.2

  # ðŸŒ Networking
  http: ^1.1.0

  # ðŸŽ¨ Fonts & UI
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8

  # ðŸ“ Maps & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # ðŸ”— Utilities
  url_launcher: ^6.2.1
  youtube_player_iframe: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt
    - assets/images/onboarding_scan.svg
    - assets/images/onboarding_map.svg
    - assets/images/onboarding_reuse.svg
